#!/usr/bin/env bash
# Regenerates the `release.*` signing config in local.properties from a
# CREDENTIAL MANAGER (source of truth), so local.properties is never the sole
# copy of the release keystore credentials.
#
# Source priority:
#   1. `pass` entries: ocdroid/release/{store-file,store-password,key-alias,key-password}
#      (GPG-encrypted; headless via a no-passphrase GPG key — see
#      .opencode/policies/build-signing.md "Release 签名"). PREFERRED.
#   2. $OCROID_RELEASE_CREDS flat file (default /home/mar/.android/ocdroid_release.creds,
#      mode 600, out-of-repo). FALLBACK.
#
# Why: local.properties is gitignored and lives INSIDE the repo, so it can be
# clobbered by repo operations (e.g. a stray `> local.properties`). The
# credentials live in the credential manager (out of repo); this script
# re-injects them. If local.properties is ever lost, just re-run this script.
#
# Usage: ./scripts/setup-signing.sh
set -euo pipefail

CREDS="${OCROID_RELEASE_CREDS:-/home/mar/.android/ocdroid_release.creds}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LP="$ROOT/local.properties"

PASS_HAS() { command -v pass >/dev/null 2>&1 && pass show "ocdroid/release/$1" >/dev/null 2>&1; }

# fetch <pass_dash_key> <creds_camel_key>  -> echoes value (pass first, creds fallback, else empty)
fetch() {
    local dash="$1" camel="$2"
    if PASS_HAS "$dash"; then
        pass show "ocdroid/release/$dash" | tr -d '\n'
    elif [ -f "$CREDS" ]; then
        grep -E "^release\.${camel}=" "$CREDS" | head -1 | cut -d= -f2-
    fi
}

STORE_FILE="$(fetch store-file storeFile || true)"
STORE_PW="$(fetch store-password storePassword || true)"
KEY_ALIAS="$(fetch key-alias keyAlias || true)"
KEY_PW="$(fetch key-password keyPassword || true)"

if [ -z "${STORE_FILE:-}" ] || [ -z "${STORE_PW:-}" ]; then
    echo "setup-signing: ERROR — could not read release.storeFile/storePassword." >&2
    echo "  Configure 'pass' (ocdroid/release/*) or provide $CREDS / set OCROID_RELEASE_CREDS." >&2
    exit 1
fi
[ -z "${KEY_ALIAS:-}" ] && KEY_ALIAS=release
[ -z "${KEY_PW:-}" ] && KEY_PW="$STORE_PW"

# Preserve sdk.dir if local.properties already has it; otherwise default.
SDK_LINE="sdk.dir=/home/mar/android-sdk"
if [ -f "$LP" ] && grep -q '^sdk.dir=' "$LP"; then
    SDK_LINE="$(grep '^sdk.dir=' "$LP")"
fi

# Report which source was used.
SRC="pass"
PASS_HAS store-password || SRC="$CREDS"

umask 077
{
    echo "$SDK_LINE"
    echo "# release signing — regenerated by scripts/setup-signing.sh (source: $SRC)"
    echo "# (do NOT hand-edit the release.* lines; edit the credential manager and re-run)"
    printf 'release.storeFile=%s\n'        "$STORE_FILE"
    printf 'release.storePassword=%s\n'    "$STORE_PW"
    printf 'release.keyAlias=%s\n'         "$KEY_ALIAS"
    printf 'release.keyPassword=%s\n'      "$KEY_PW"
} > "$LP"
chmod 600 "$LP"

echo "setup-signing: wrote $LP (source: $SRC)"
echo "  keystore: $STORE_FILE"
